--- 
author: ~
distribution_type: module
generated_by: Module::Install version 0.68
license: unknown
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Jifty-Plugin-Multipage
no_index: 
  directory: 
    - inc
    - t
requires: 
  Moose: 0
version: 0.01
